steps:
  - name: 'gcr.io/cloud-builders/docker'
    env:
      - 'DOCKER_BUILDKIT=1'
    args:
      - 'build'
      - '--secret'
      - 'id=DATABASE_URL,src=/workspace/secrets/DATABASE_URL'
      - '-t'
      - 'asia-northeast1-docker.pkg.dev/bonsai-410001/cloud-run-source-deploy/bonsai/bonsai:$SHORT_SHA'
      - '.'
      
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - push
      - 'asia-northeast1-docker.pkg.dev/bonsai-410001/cloud-run-source-deploy/bonsai/bonsai:$SHORT_SHA'

  - name: 'gcr.io/cloud-builders/gcloud'
    args:
      - run
      - deploy
      - bonsai
      - '--image'
      - 'asia-northeast1-docker.pkg.dev/bonsai-410001/cloud-run-source-deploy/bonsai/bonsai:$SHORT_SHA'
      - '--region'
      - 'asia-northeast1'
      - '--platform'
      - 'managed'
      - '--allow-unauthenticated'

options:
  logging: CLOUD_LOGGING_ONLY

availableSecrets:
  secretManager:
    - versionName: 'projects/bonsai-410001/secrets/DATABASE_URL/versions/latest'
      # env フィールドを削除して、ファイルとしてのみ利用する

images:
  - 'asia-northeast1-docker.pkg.dev/bonsai-410001/cloud-run-source-deploy/bonsai/bonsai:$SHORT_SHA'
