steps:
  # ビルドステップ
  - name: 'gcr.io/cloud-builders/docker'
    env:
      - 'DOCKER_BUILDKIT=1'
    args:
      - 'build'
      - '-t'
      - 'asia-northeast1-docker.pkg.dev/bonsai-410001/cloud-run-source-deploy/bonsai/bonsai:$SHORT_SHA'
      - '.'

  # イメージをプッシュ
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - 'asia-northeast1-docker.pkg.dev/bonsai-410001/cloud-run-source-deploy/bonsai/bonsai:$SHORT_SHA'

  # マイグレーション用のステップを実行
  - name: 'gcr.io/cloud-builders/docker'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        # Secret Managerからデータベース接続情報を取得
        export DATABASE_URL=$(gcloud secrets versions access latest --secret=DATABASE_URL)
        
        # 一時的にコンテナを実行してマイグレーションを実行
        docker run --rm \
          -e DATABASE_URL="$$DATABASE_URL" \
          -e RUN_MIGRATIONS=true \
          asia-northeast1-docker.pkg.dev/bonsai-410001/cloud-run-source-deploy/bonsai/bonsai:$SHORT_SHA \
          npx prisma migrate deploy

  # Cloud Runにデプロイ（マイグレーションなし）
  - name: 'gcr.io/cloud-builders/gcloud'
    args:
      - 'run'
      - 'deploy'
      - 'bonsai'
      - '--image'
      - 'asia-northeast1-docker.pkg.dev/bonsai-410001/cloud-run-source-deploy/bonsai/bonsai:$SHORT_SHA'
      - '--region'
      - 'asia-northeast1'
      - '--platform'
      - 'managed'
      - '--allow-unauthenticated'
      - '--set-env-vars'
      - 'RUN_MIGRATIONS=false'
      - '--update-secrets'
      - 'DATABASE_URL=DATABASE_URL:latest'

options:
  logging: CLOUD_LOGGING_ONLY

images:
  - 'asia-northeast1-docker.pkg.dev/bonsai-410001/cloud-run-source-deploy/bonsai/bonsai:$SHORT_SHA'
