steps:
  # ビルドステップ
  - name: 'gcr.io/cloud-builders/docker'
    env:
      - 'DOCKER_BUILDKIT=1'
    args:
      - 'build'
      - '-t'
      - 'asia-northeast1-docker.pkg.dev/bonsai-410001/cloud-run-source-deploy/bonsai/bonsai:$SHORT_SHA'
      - '.'

  # イメージをプッシュ
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - 'asia-northeast1-docker.pkg.dev/bonsai-410001/cloud-run-source-deploy/bonsai/bonsai:$SHORT_SHA'

  # マイグレーション用のジョブを実行（Secret Managerから直接シークレットを取得）
  - name: 'gcr.io/google-appengine/exec-wrapper'
    args:
      - '-i'
      - 'asia-northeast1-docker.pkg.dev/bonsai-410001/cloud-run-source-deploy/bonsai/bonsai:$SHORT_SHA'
      - '-s'
      - 'bonsai-410001'
      - '--'
      - 'sh'
      - '-c'
      - |
        export DATABASE_URL=$$(gcloud secrets versions access latest --secret=DATABASE_URL)
        export RUN_MIGRATIONS=true
        npx prisma migrate deploy

  # Cloud Runにデプロイ（マイグレーションなし）
  - name: 'gcr.io/cloud-builders/gcloud'
    args:
      - 'run'
      - 'deploy'
      - 'bonsai'
      - '--image'
      - 'asia-northeast1-docker.pkg.dev/bonsai-410001/cloud-run-source-deploy/bonsai/bonsai:$SHORT_SHA'
      - '--region'
      - 'asia-northeast1'
      - '--platform'
      - 'managed'
      - '--allow-unauthenticated'
      - '--set-env-vars'
      - 'RUN_MIGRATIONS=false'
      - '--update-secrets'
      - 'DATABASE_URL=DATABASE_URL:latest'

options:
  logging: CLOUD_LOGGING_ONLY

images:
  - 'asia-northeast1-docker.pkg.dev/bonsai-410001/cloud-run-source-deploy/bonsai/bonsai:$SHORT_SHA'
